AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGateway:
    Name: goto
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        CertificateArn: arn:aws:acm:ap-northeast-1:486414336274:certificate/5b205c4d-aec3-4ee1-b5e5-3b338026dcf4
        DomainName: go.dark-kuins.net
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: goto
      Runtime: go1.x
      FunctionName: goto
      Timeout: 30
      Role: arn:aws:iam::486414336274:role/goto # ここまできてだけど、CAPABILITY_IAM手元のマシンにつけたくないなと手で作った。
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
          DYNAMODB_TABLE_NAME: !Ref GotoTable
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: any
        Proxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: any
  GotoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: goto
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
